# Generated by Django 5.1.4 on 2025-11-25 18:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='delivery_fee',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='delivery_latitude',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='delivery_longitude',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='delivery_method',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='koraquest_commission_amount',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='koraquest_commission_sent',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='koraquest_user',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='pickup_confirmed_at',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='vendor_payment_amount',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='vendor_payment_sent',
        ),
        migrations.AddField(
            model_name='post',
            name='bathrooms',
            field=models.IntegerField(blank=True, help_text='Number of bathrooms (for houses)', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='bedrooms',
            field=models.IntegerField(blank=True, help_text='Number of bedrooms (for houses)', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('needs_renovation', 'Needs Renovation')], default='good', help_text='Condition of the property/item', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='inquiry_count',
            field=models.IntegerField(default=0, help_text='Number of inquiries received'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is listing currently active?'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_furnished',
            field=models.BooleanField(default=False, help_text='Is the property furnished? (for houses)'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_sold',
            field=models.BooleanField(default=False, help_text='Has the property been sold?'),
        ),
        migrations.AddField(
            model_name='post',
            name='location_address',
            field=models.CharField(blank=True, help_text='Full address', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='location_city',
            field=models.CharField(blank=True, help_text='City', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='location_district',
            field=models.CharField(blank=True, help_text='District/Region', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='location_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='location_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='parking_spaces',
            field=models.IntegerField(blank=True, default=0, help_text='Number of parking spaces', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='property_type',
            field=models.CharField(choices=[('house', 'House'), ('land', 'Land Plot'), ('furniture', 'Furniture')], default='furniture', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='size_sqm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Size in square meters', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='view_count',
            field=models.IntegerField(default=0, help_text='Number of times listing was viewed'),
        ),
        migrations.AddField(
            model_name='post',
            name='year_built',
            field=models.IntegerField(blank=True, help_text='Year property was built', null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='documents_uploaded',
            field=models.BooleanField(default=False, help_text='Required documents uploaded'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Final agreed price', max_digits=12),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Payment transaction reference', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='property',
            field=models.ForeignKey(blank=True, help_text='Property being purchased', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='authentication.post'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='transaction_notes',
            field=models.TextField(blank=True, help_text='Transaction notes', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('villa', 'Villa'), ('townhouse', 'Townhouse'), ('duplex', 'Duplex'), ('studio', 'Studio'), ('bungalow', 'Bungalow'), ('residential_land', 'Residential Land'), ('commercial_land', 'Commercial Land'), ('agricultural_land', 'Agricultural Land'), ('industrial_land', 'Industrial Land'), ('mixed_use_land', 'Mixed-Use Land'), ('living_room', 'Living Room Furniture'), ('bedroom', 'Bedroom Furniture'), ('kitchen', 'Kitchen Furniture'), ('office', 'Office Furniture'), ('outdoor', 'Outdoor Furniture'), ('storage', 'Storage Furniture')], default='living_room', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='inventory',
            field=models.IntegerField(default=1, help_text='Number of items available'),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('momo', 'Mobile Money'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('other', 'Other')], default='momo', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='quantity',
            field=models.IntegerField(default=1, help_text='Quantity (usually 1 for property)'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('payment_confirmed', 'Payment Confirmed'), ('documents_processing', 'Documents Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('staff', 'Staff'), ('vendor', 'Vendor'), ('inzulink', 'InzuLink')], default='user', max_length=20),
        ),
        migrations.CreateModel(
            name='ListingFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_fee', models.DecimalField(decimal_places=2, help_text='Daily fee to keep listing active', max_digits=10)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, help_text='When listing fee period ends', null=True)),
                ('days_paid', models.IntegerField(default=0, help_text='Number of days paid for')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('auto_renew', models.BooleanField(default=False, help_text='Automatically renew listing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_fees', to='authentication.post')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_fees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('message', models.TextField(help_text="Buyer's message or questions")),
                ('phone_contact', models.CharField(blank=True, help_text="Buyer's contact phone", max_length=15, null=True)),
                ('email_contact', models.EmailField(blank=True, help_text="Buyer's contact email", max_length=254, null=True)),
                ('status', models.CharField(choices=[('new', 'New Inquiry'), ('contacted', 'Vendor Contacted'), ('viewing_scheduled', 'Viewing Scheduled'), ('offer_made', 'Offer Made'), ('negotiating', 'Negotiating'), ('accepted', 'Accepted'), ('completed', 'Sale Completed'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='new', max_length=30)),
                ('offered_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price offered by buyer', max_digits=12, null=True)),
                ('preferred_viewing_date', models.DateTimeField(blank=True, help_text='Preferred date to view property', null=True)),
                ('viewing_confirmed', models.BooleanField(default=False)),
                ('viewing_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responded_at', models.DateTimeField(blank=True, help_text='When vendor responded', null=True)),
                ('vendor_notes', models.TextField(blank=True, help_text="Vendor's notes about this inquiry", null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='authentication.post')),
            ],
            options={
                'verbose_name_plural': 'Property Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='inquiry',
            field=models.ForeignKey(blank=True, help_text='Related inquiry if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='authentication.propertyinquiry'),
        ),
    ]
