# Generated by Django 5.1.4 on 2025-12-02 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_purchase_delivery_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('blocked', 'Blocked')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('buyer_last_read', models.DateTimeField(blank=True, null=True)),
                ('seller_last_read', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(help_text='The user initiating the conversation (potential buyer)', on_delete=django.db.models.deletion.CASCADE, related_name='buyer_conversations', to=settings.AUTH_USER_MODEL)),
                ('inquiry', models.ForeignKey(blank=True, help_text='Related property inquiry if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='authentication.propertyinquiry')),
                ('property', models.ForeignKey(blank=True, help_text='The property this conversation is about', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='authentication.post')),
                ('seller', models.ForeignKey(help_text='The property owner/vendor', on_delete=django.db.models.deletion.CASCADE, related_name='seller_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_message_at', '-created_at'],
                'unique_together': {('buyer', 'seller', 'property')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Message text content')),
                ('attachment', models.FileField(blank=True, help_text='Optional file attachment', null=True, upload_to='chat_attachments/')),
                ('attachment_type', models.CharField(blank=True, help_text='Type of attachment: image, document, etc.', max_length=20, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='authentication.conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['conversation', 'created_at'], name='authenticat_convers_1ff675_idx'), models.Index(fields=['sender', 'created_at'], name='authenticat_sender__84e625_idx')],
            },
        ),
    ]
