# Generated by Django 5.1.4 on 2025-12-16 19:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_listingfee_momo_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text='When item was delivered', null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='delivery_address',
            field=models.CharField(blank=True, help_text='Delivery address for furniture items', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='delivery_notes',
            field=models.TextField(blank=True, help_text='Notes about delivery', null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='delivery_phone',
            field=models.CharField(blank=True, help_text='Contact phone for delivery', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='delivery_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('delivery_failed', 'Delivery Failed')], help_text='Delivery status (for furniture items)', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='shipped_at',
            field=models.DateTimeField(blank=True, help_text='When item was shipped', null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='tracking_number',
            field=models.CharField(blank=True, help_text='Tracking number for shipment', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listingfee',
            name='momo_status',
            field=models.CharField(blank=True, help_text='Paypack payment status: PENDING, SUCCESSFUL, FAILED (reusing field name)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='listingfee',
            name='momo_transaction_id',
            field=models.CharField(blank=True, help_text='Paypack transaction reference ID (reusing field name)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listingfee',
            name='payment_method',
            field=models.CharField(default='manual', help_text='Payment method: manual, paypack', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('paypack', 'Paypack'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('other', 'Other')], default='paypack', max_length=20),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='authentication.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='authentication.post')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('cart', 'product')},
            },
        ),
    ]
